name: Bug Report
description: Report a bug.
title: "[Bug]: "
labels: ["bug"]
body: 
  - type: markdown
    attributes:
      value: Please see if there is an already existing Issue with the same bug before posting a Bug Report! 
  - type: dropdown
    attributes:
      label: Bug Severity
      options:
        - High
        - Medium
        - Low
  - type: textarea
    attributes:
      label: The Bug
      placeholder: Describe the bug here clearly
    validations:
      required: true
  - type: input
    attributes:
      label: F3 screenshot
      description: Attach the full F3 screenshot if possible
  - type: markdown
    attributes:
      value: If you cannot attach an F3 screenshot then please provide the information below!
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - Mac
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Driver Vendor
      options: 
        - Nivida
        - AMD
        - Intel
        - ATI
        - Mesa
        - XORG
        - Other
  - type: dropdown
    attributes:
      label: Shader Loader
      description: This shader is only built for Iris, other shader loaders may not work!
      options: 
        - Iris
        - Optifine
      validations:
        required: true
  - type: input
    attributes:
      label: GPU Name
  - type: input
    attributes:
      label: Minecraft Version
  - type: input
    attributes:
      label: Minecraft Client
      value: Official
  - type: input
    attributes:
      label: Shader Version
      placeholder: Featherweight v0.0.0.0.tag
      value: Featherweight v...
  - type: textarea
    attributes:
      label: Suspect (rendering) mods
  - type: textarea
    attributes:
      label: Cause of bug
      description: Put [Unknown cause] if you cannot find the cause, please try to isolate the cause to make resolving the issue easier!
      placeholder: Causes can be mods, minecraft client, shader setting, etc
    validations:
      required: true
  - type: input
    attributes:
      label: Shader Settings
      description: Include the shader settings file (`shaderpacks/SomeShaderName.txt`) if possible  
- type: textarea
    attributes:
      label: Extra
      description: Put extra information or information that does not fit the form here
