screen.columns = 3
screen = \
    [GENERAL] [LIGHTING] [ATMOSPHERE] \
    [DISTANT_HORIZONS] <empty> <empty> \
    [DEBUG] 
screen.GENERAL = MIP_MAP_BIAS PIXELIZATION
screen.DISTANT_HORIZONS = DH_FADE_START DH_FADE_QUALITY
screen.ATMOSPHERE.columns = 3
screen.ATMOSPHERE = \
    FOG_DENSITY FOG_START FOG_END AMBIENT_REFLECTION_QUALITY \
    [CLOUDS_TODO] [GODRAYS]
    screen.GODRAYS = [SUNRAYS] [SUN_SHAFTS_TODO]
        screen.SUNRAYS.columns = 3
        screen.SUNRAYS = \
            SUNRAYS_MODE SUNRAYS_STRENGTH SUNRAYS_SPREAD \
            SUNRAYS_SAMPLES SUNRAYS_FAKE_SAMPLES SUNRAYS_AUTO_FAKE_SAMPLES \
            SUNRAYS_ORIGIN_SIZE SUNRAYS_ORIGIN_SHAPE SUNRAYS_MAX_TRANSPARENCY \
            SUNRAYS_TINT_STRENGTH <empty> <empty> \
            <empty> <empty> <empty> \
            SUNRAYS_SAMPLES_OVERRIDE
screen.LIGHTING.columns = 3
screen.LIGHTING = \
 sunPathRotation LIGHT_BRIGHTNESS [SHADING] \
 [LIGHTS] [SHADOWS] \
 [AMBIENT] [AMBIENT_OCCLUSION]
    screen.SHADING = NORMAL_STRENGTH SPECULAR
    screen.AMBIENT = [COLOR] 
        screen.COLOR = AMBIENT_R AMBIENT_G AMBIENT_B
        screen.COLOR.columns = 4
    screen.AMBIENT_OCCLUSION = AMBIENT_OCCLUSION
    screen.SHADOWS = \
        SHADOWS SHADOW_FILTER \
        shadowMapResolution shadowDistance \
        SHADOW_NEAR_DISTORT \
        <empty> <empty> \
        [SOFT_SHADOWS] [SHADOW_FADE_OUT] \
        [SHADOW_ADVANCED]
        screen.SOFT_SHADOWS = SHADOW_SOFTNESS SHADOW_SAMPLES [VPS]
            screen.VPS = MAX_SOFTNESS_DISPLAY MIN_SOFTNESS_DISPLAY PCSS_SEARCH_SAMPLES PCSS_SEARCH_OFFSET_BIAS [AUTO_PCSS]
                screen.AUTO_PCSS = PCSS_SAMPLES_MULT PCSS_MIN_SAMPLES PCSS_MAX_SAMPLES
        screen.SHADOW_FADE_OUT = SHADOW_FADE_OUT SHADOW_FADE_OUT_START_DISPLAY SHADOW_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_START_DISPLAY
        screen.SHADOW_ADVANCED = SHADOW_MIP_MAP_BIAS shadowIntervalSize Z_BIAS_DISPLAY DISTORT_USING_LIGHT_ANGLE PRESET_PCF_PATTERNS

sliders = AMBIENT_REFLECTION_QUALITY \ NORMAL_STRENGTH \ PIXELIZATION \ DH_FADE_QUALITY DH_FADE_START \ FOG_DENSITY FOG_START FOG_END \ SUNRAYS_TINT_STRENGTH SUNRAYS_STRENGTH SUNRAYS_SPREAD SUNRAYS_SAMPLES SUNRAYS_FAKE_SAMPLES SUNRAYS_ORIGIN_SIZE SUNRAYS_MODE SUNRAYS_MAX_TRANSPARENCY SUNRAYS_SAMPLES_OVERRIDE \ MAX_SOFTNESS_DISPLAY MIN_SOFTNESS_DISPLAY PCSS_SEARCH_SAMPLES PCSS_SEARCH_OFFSET_BIAS PCSS_SAMPLES_MULT PCSS_MIN_SAMPLES PCSS_MAX_SAMPLES SHADOW_SOFTNESS_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_START_DISPLAY MAX_AMBIENT_OCCLUSION SHADOW_FILTER SHADOW_SAMPLES SHADOW_SOFTNESS SHADOW_FADE_OUT_START_DISPLAY SHADOW_FADE_OUT_STRENGTH SHADOW_FADE_OUT SHADOW_MIP_MAP_BIAS MIP_MAP_BIAS sunPathRotation Z_BIAS_DISPLAY SHADOW_NEAR_DISTORT shadowDistance shadowMapResolution shadowIntervalSize CLOUD_FADE_Z_LIMIT_ADD CLOUD_ALPHA CLOUD_FADE_IN_INTENSITY CLOUD_AMBIENT_STRENGTH AMBIENT_R AMBIENT_G AMBIENT_B LIGHT_SOURCE_BRIGHTNESS LIGHT_BRIGHTNESS CLOUD_AMBIENT_STRENGTH TRANSPARENCY_OVERLAP_NOISE \
_SHOW_POSITION _SHADOW_FADE_OUT _SHOW_SHADOWMAP _ISOLATE_DIFFUSE _SHOW_DH_DEPTH _SHOW_ROUGHNESS _SHOW_REFLECTANCE _SHOW_POROSITY_SSS _SHOW_EMISSION _SHOW_NORMALS _SHOW_AO _SHOW_HEIGHT _SHOW_DEPTHMAP \ 

## DEBUG MENU, Feel free to uncomment, commented out for performance reasons
# TURN_ON_DEBUG_MODE_HERE
screen.DEBUG = DEBUG _SHADOW_FADE_OUT [_ISOLATE] [_TEXTURES]
screen._ISOLATE = _ISOLATE_DIFFUSE _ISOLATE_VERT_COLOR _ISOLATE_LIGHTMAP
screen._TEXTURES = _SHOW_SHADOWMAP _SHOW_DH_DEPTH _SHOW_DEPTHMAP _SHOW_POSITION <empty> <empty> _SHOW_ROUGHNESS _SHOW_REFLECTANCE _SHOW_POROSITY_SSS _SHOW_EMISSION _SHOW_NORMALS _SHOW_AO _SHOW_HEIGHT
## DEBUG MENU END ##

uniform.float.constantMoodSmooth = smooth(constantMood, 8, 5)
uniform.float.rainfallSmooth = smooth(rainfall, 10, 4)
uniform.float.temperatureSmooth = smooth(temperature, 12, 12)
variable.float.roomTemperatureDiff = (1-abs(0.75 - temperatureSmooth))
uniform.float.rain = wetness * mix(rainfallSmooth, (roomTemperatureDiff * edge(0, roomTemperatureDiff)), 0.66)

# Day Cycle, EXTRA_SETTINGS
variable.float.SUNRISE0 = 0
variable.float.SUNRISE1 = 1
variable.float.MORNING = 0.125
variable.float.NOON = 0.25
variable.float.AFTERNOON = 0.375
variable.float.SUNSET = 0.5
variable.float.NIGHT_START = 0.55
variable.float.MIDNIGHT = 0.75
variable.float.NIGHT_END = 0.95
variable.vec4.COLOR_SUNRISE = vec4(0.984, 0.702, 0.275, 0.85)
variable.vec4.COLOR_MORNING = vec4(0.941, 0.855, 0.588, 1)
variable.vec4.COLOR_NOON = vec4(0.941, 0.898, 0.765, 1)
variable.vec4.COLOR_AFTERNOON = vec4(0.9625, 0.807, 0.4157, 1)
variable.vec4.COLOR_SUNSET = vec4(0.984, 0.6235, 0.2627, 0.85)
variable.vec4.COLOR_NIGHT_START = vec4(0.1451, 0.14513, 0.23137, 0.8)
variable.vec4.COLOR_MIDNIGHT = vec4(0.0588, 0.04706, 0.1412, 0.75)
variable.vec4.COLOR_NIGHT_END = vec4(0, 0, 0.035, 0.8)
variable.vec4.COLOR_RAIN = vec4(0.306, 0.408, 0.506, 0.8)
variable.float.ALPHA_NIGHT_END = (sunAngle - NIGHT_END) / (SUNRISE1 - NIGHT_END)
variable.float.ALPHA_MIDNIGHT = (sunAngle - MIDNIGHT) / (NIGHT_END - MIDNIGHT)
variable.float.ALPHA_NIGHT_START = (sunAngle - NIGHT_START) / (MIDNIGHT - NIGHT_START)
variable.float.ALPHA_SUNSET = (sunAngle - SUNSET) / (NIGHT_START - SUNSET)
variable.float.ALPHA_AFTERNOON = (sunAngle - AFTERNOON) / (SUNSET - AFTERNOON)
variable.float.ALPHA_NOON = (sunAngle - NOON) / (AFTERNOON - NOON)
variable.float.ALPHA_MORNING = (sunAngle - MORNING) / (NOON - MORNING)
variable.float.ALPHA_SUNRISE = (sunAngle - SUNRISE0) / (MORNING - SUNRISE0)
# EXTRA-SETTINGS-END

# Lerps between the various day cycle colors
# uniform.vec4.lightColor = vec4(1,1,1, 1) * if( \
#     sunAngle >= SUNRISE0, COLOR_SUNRISE + (COLOR_MORNING-COLOR_SUNRISE) * vec4(ALPHA_SUNRISE, ALPHA_SUNRISE, ALPHA_SUNRISE, ALPHA_SUNRISE), \
#     if(sunAngle >= MORNING, COLOR_MORNING + (COLOR_NOON-COLOR_MORNING) * vec4(ALPHA_MORNING, ALPHA_MORNING, ALPHA_MORNING, ALPHA_MORNING), \
#     if(sunAngle >= NOON, COLOR_NOON + (COLOR_AFTERNOON-COLOR_NOON) * vec4(ALPHA_NOON, ALPHA_NOON, ALPHA_NOON, ALPHA_NOON), \
#     if(sunAngle >= AFTERNOON, COLOR_AFTERNOON + (COLOR_SUNSET-COLOR_AFTERNOON) * vec4(ALPHA_AFTERNOON, ALPHA_AFTERNOON, ALPHA_AFTERNOON, ALPHA_AFTERNOON), \
#     if(sunAngle >= SUNSET, COLOR_SUNSET + (COLOR_NIGHT_START-COLOR_SUNSET) * vec4(ALPHA_SUNSET, ALPHA_SUNSET, ALPHA_SUNSET, ALPHA_SUNSET), \
#     if(sunAngle >= NIGHT_START,COLOR_NIGHT_START + (COLOR_MIDNIGHT-COLOR_NIGHT_START) * vec4(ALPHA_NIGHT_START, ALPHA_NIGHT_START, ALPHA_NIGHT_START, ALPHA_NIGHT_START), \
#     if(sunAngle >= MIDNIGHT, COLOR_MIDNIGHT + (COLOR_NIGHT_END-COLOR_MIDNIGHT) *  vec4(ALPHA_MIDNIGHT, ALPHA_MIDNIGHT, ALPHA_MIDNIGHT, ALPHA_MIDNIGHT), \
#     if(sunAngle >= NIGHT_END, COLOR_NIGHT_END + (COLOR_SUNRISE-COLOR_NIGHT_END) * vec4(ALPHA_NIGHT_END, ALPHA_NIGHT_END, ALPHA_NIGHT_END, ALPHA_NIGHT_END), \
#     vec4(1,1,0,1)))))))))

uniform.vec4.lightColor = vec4(1,1,1, LIGHT_BRIGHTNESS) * if( \
    sunAngle >= NIGHT_END, COLOR_NIGHT_END + (COLOR_SUNRISE-COLOR_NIGHT_END) * vec4(ALPHA_NIGHT_END, ALPHA_NIGHT_END, ALPHA_NIGHT_END, ALPHA_NIGHT_END), \
    if(sunAngle >= MIDNIGHT, COLOR_MIDNIGHT + (COLOR_NIGHT_END-COLOR_MIDNIGHT) *  vec4(ALPHA_MIDNIGHT, ALPHA_MIDNIGHT, ALPHA_MIDNIGHT, ALPHA_MIDNIGHT), \
    if(sunAngle >= NIGHT_START,COLOR_NIGHT_START + (COLOR_MIDNIGHT-COLOR_NIGHT_START) * vec4(ALPHA_NIGHT_START, ALPHA_NIGHT_START, ALPHA_NIGHT_START, ALPHA_NIGHT_START), \
    if(sunAngle >= SUNSET, COLOR_SUNSET + (COLOR_NIGHT_START-COLOR_SUNSET) * vec4(ALPHA_SUNSET, ALPHA_SUNSET, ALPHA_SUNSET, ALPHA_SUNSET), \
    if(sunAngle >= AFTERNOON, COLOR_AFTERNOON + (COLOR_SUNSET-COLOR_AFTERNOON) * vec4(ALPHA_AFTERNOON, ALPHA_AFTERNOON, ALPHA_AFTERNOON, ALPHA_AFTERNOON), \
    if(sunAngle >= NOON, COLOR_NOON + (COLOR_AFTERNOON-COLOR_NOON) * vec4(ALPHA_NOON, ALPHA_NOON, ALPHA_NOON, ALPHA_NOON), \
    if(sunAngle >= MORNING, COLOR_MORNING + (COLOR_NOON-COLOR_MORNING) * vec4(ALPHA_MORNING, ALPHA_MORNING, ALPHA_MORNING, ALPHA_MORNING), \
    if(sunAngle >= SUNRISE0, COLOR_SUNRISE + (COLOR_MORNING-COLOR_SUNRISE) * vec4(ALPHA_SUNRISE, ALPHA_SUNRISE, ALPHA_SUNRISE, ALPHA_SUNRISE), \
    vec4(1,1,0,1)))))))))

## Handle Settings
#if SUNRAYS_MODE == 0
program.composite10.enabled = false
#endif
#if SHADOWS == 0
shadow.enabled = false
#endif
#if DEBUG == 0
program.composite99.enabled = false
#endif

separateAo=true
iris.features.required=SEPARATE_HARDWARE_SAMPLERS
dhShadow.enabled=true