screen.columns = 3
screen = \
    [GENERAL] [LIGHTING] [ATMOSPHERE] \
    [DISTANT_HORIZONS] <empty> <empty> \
    [DEBUG] 
screen.GENERAL = MIP_MAP_BIAS
screen.DISTANT_HORIZONS = DH_FADE_START DH_FADE_QUALITY
screen.ATMOSPHERE.columns = 3
screen.ATMOSPHERE = \
    FOG_DENSITY FOG_START FOG_END \
    [CLOUDS_TODO] [GODRAYS]
    screen.GODRAYS = [SUNRAYS] [SUN_SHAFTS_TODO]
        screen.SUNRAYS.columns = 3
        screen.SUNRAYS = \
            SUNRAYS_MODE SUNRAYS_STRENGTH SUNRAYS_SPREAD \
            SUNRAYS_SAMPLES SUNRAYS_FAKE_SAMPLES SUNRAYS_AUTO_FAKE_SAMPLES \
            SUNRAYS_ORIGIN_SIZE SUNRAYS_ORIGIN_SHAPE SUNRAYS_MAX_TRANSPARENCY \
            SUNRAYS_TINT_STRENGTH <empty> <empty> \
            <empty> <empty> <empty> \
            SUNRAYS_SAMPLES_OVERRIDE
screen.LIGHTING.columns = 3
screen.LIGHTING = \
 sunPathRotation [SHADING] \
 [LIGHTS] [SHADOWS] \
 [AMBIENT] [AMBIENT_OCCLUSION]
    screen.SHADING = SHADING MAX_AMBIENT_OCCLUSION
    screen.LIGHTS = [PERFORMANCE] LIGHT_SOURCE_BRIGHTNESS LIGHT_BRIGHTNESS
        screen.PERFORMANCE = LIGHT_QUALITY
    screen.AMBIENT = [COLOR]
        screen.COLOR = AMBIENT_R AMBIENT_G AMBIENT_B AMBIENT_STRENGTH
        screen.COLOR.columns = 4
    screen.AMBIENT_OCCLUSION = AMBIENT_OCCLUSION
    screen.SHADOWS = \
        SHADOWS SHADOW_FILTER \
        shadowMapResolution shadowDistance \
        SHADOW_NEAR_DISTORT SHADOW_PIXELIZATION_DISPLAY \
        <empty> <empty> \
        [SOFT_SHADOWS] [SHADOW_FADE_OUT] \
        [SHADOW_ADVANCED]
        screen.SOFT_SHADOWS = SHADOW_SOFTNESS SHADOW_SAMPLES [VPS]
            screen.VPS = MAX_SOFTNESS_DISPLAY MIN_SOFTNESS_DISPLAY PCSS_SEARCH_SAMPLES PCSS_SEARCH_OFFSET_BIAS [AUTO_PCSS]
                screen.AUTO_PCSS = PCSS_SAMPLES_MULT PCSS_MIN_SAMPLES PCSS_MAX_SAMPLES
        screen.SHADOW_FADE_OUT = SHADOW_FADE_OUT SHADOW_FADE_OUT_START_DISPLAY SHADOW_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_START_DISPLAY
        screen.SHADOW_ADVANCED = SHADOW_MIP_MAP_BIAS shadowIntervalSize Z_BIAS_DISPLAY DISTORT_USING_LIGHT_ANGLE PRESET_PCF_PATTERNS

sliders = \ DH_FADE_QUALITY DH_FADE_START \ FOG_DENSITY FOG_START FOG_END \ SUNRAYS_TINT_STRENGTH SUNRAYS_STRENGTH SUNRAYS_SPREAD SUNRAYS_SAMPLES SUNRAYS_FAKE_SAMPLES SUNRAYS_ORIGIN_SIZE SUNRAYS_MODE SUNRAYS_MAX_TRANSPARENCY SUNRAYS_SAMPLES_OVERRIDE \ MAX_SOFTNESS_DISPLAY MIN_SOFTNESS_DISPLAY PCSS_SEARCH_SAMPLES PCSS_SEARCH_OFFSET_BIAS PCSS_SAMPLES_MULT PCSS_MIN_SAMPLES PCSS_MAX_SAMPLES SHADOW_SOFTNESS_FADE_OUT_STRENGTH SHADOW_SOFTNESS_FADE_OUT_START_DISPLAY MAX_AMBIENT_OCCLUSION SHADOW_FILTER SHADOW_SAMPLES SHADOW_SOFTNESS SHADOW_FADE_OUT_START_DISPLAY SHADOW_FADE_OUT_STRENGTH SHADOW_FADE_OUT SHADOW_MIP_MAP_BIAS MIP_MAP_BIAS sunPathRotation SHADOW_PIXELIZATION_DISPLAY Z_BIAS_DISPLAY SHADOW_NEAR_DISTORT shadowDistance shadowMapResolution shadowIntervalSize CLOUD_FADE_Z_LIMIT_ADD CLOUD_ALPHA CLOUD_FADE_IN_INTENSITY CLOUD_AMBIENT_STRENGTH AMBIENT_R AMBIENT_G AMBIENT_B AMBIENT_STRENGTH LIGHT_SOURCE_BRIGHTNESS LIGHT_BRIGHTNESS CLOUD_AMBIENT_STRENGTH TRANSPARENCY_OVERLAP_NOISE \
_SHOW_POSITION _SHADOW_FADE_OUT _SHOW_SHADOWMAP _ISOLATE_DIFFUSE _SHOW_DH_DEPTH _SHOW_ROUGHNESS _SHOW_REFLECTANCE _SHOW_POROSITY_SSS _SHOW_EMISSION _SHOW_NORMALS _SHOW_AO _SHOW_HEIGHT _SHOW_DEPTHMAP \ 

## DEBUG MENU, Feel free to uncomment, commented out for performance reasons
# TURN_ON_DEBUG_MODE_HERE
screen.DEBUG = DEBUG _SHADOW_FADE_OUT [_ISOLATE] [_TEXTURES]
screen._ISOLATE = _ISOLATE_DIFFUSE _ISOLATE_VERT_COLOR _ISOLATE_LIGHTMAP
screen._TEXTURES = _SHOW_SHADOWMAP _SHOW_DH_DEPTH _SHOW_DEPTHMAP _SHOW_POSITION <empty> <empty> _SHOW_ROUGHNESS _SHOW_REFLECTANCE _SHOW_POROSITY_SSS _SHOW_EMISSION _SHOW_NORMALS _SHOW_AO _SHOW_HEIGHT
## DEBUG MENU END ##


uniform.float.constantMoodSmooth = smooth(constantMood, 8, 5)
uniform.float.rainfallSmooth = smooth(rainfall, 10, 4)
uniform.float.temperatureSmooth = smooth(temperature, 12, 12)
variable.float.roomTemperatureDiff = (1-abs(0.75 - temperatureSmooth))
uniform.float.rain = wetness * mix(rainfallSmooth, (roomTemperatureDiff * edge(0, roomTemperatureDiff)), 0.66)



## Handle Settings
#if SUNRAYS_MODE == 0
program.composite10.enabled = false
#endif
#if SHADOWS == 0
shadow.enabled = false
#endif
#if DEBUG == 0
program.composite99.enabled = false
#endif

separateAo=true
iris.features.required=SEPARATE_HARDWARE_SAMPLERS
dhShadow.enabled=true